resource "aws_s3_bucket" "Just_an_demo" {
#Can only utilise any of one b/w bucket and bucket_prefix 
# AS bucket will be a random generated by terraform
#    bucket = "clitoris_restart"
    bucket_prefix = "clitoris"
    force_destroy = true
    object_lock_enabled = true

    tags = {
        name = "Just_an_demo"
    }
}

resource "aws_s3_object" "labia"{
    bucket = aws_s3_bucket.Just_an_demo.bucket
    key = "demo.webp"
    source = "${path.module}/demo.webp"
    etag   = filemd5("${path.module}/demo.webp")
}
